#Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Waltonians
tagline:          'Celebrating Community in Walton, NY'
description:      'Celebrating community in Walton, NY. Brought to you by <a href="https://twitter.com/c_t_ogden" target="_blank">Chris Ogden</a>.'
url:              http://waltonians.org
baseurl:          /

author:
  name:           'Chris Ogden'
  url:            https://twitter.com/c_t_ogden

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Walton-NY/Walton-NY
